### ISSUE TITLE
JavaDocs

### ISSUE THREAD

**Issue by coaster3000** [Ranzdo/MethodCommand#1]
Java docs added to source code would help many users use this. Even if there is a wiki. It helps users not need to open webpages constantly.

I am also willing to document it if possible. BUt however I have no clue how to use annotations. 
As in creating custom ones.

**Comment by Ranzdo** [comment]
I have made some javadocs but it is not finished (JavaDocs can be found at http://ci.saerix.com/jenkins/job/MethodCommand/Javadocs/).

I don't see a need to code new annonations, let alone new features. I pretty much sees this project complete on the feature side and now just need better documentation, bug fixing and keeping up to date with bukkit. However, if you have any new feature that you would like to see, open an new issue and describe it and we will see what ideas we can come up with ^^.

In the coming days I will try to write as much javadocs as possible to complete this project. There are so many features that are not documented that are really useful, so keep an eye on that.
