### ISSUE TITLE
Wiki Does Not Descrive flags

### ISSUE THREAD

**Issue by coaster3000** [Ranzdo/MethodCommand#2]
I have tried looking through source code so i can figure out how to use flags.

I would have helped post it on wiki too if i did find it.

But i am completely lost and can not find out how to use flags for commands...

I am not 100% good on annotations yet on java. Especially reflection.

**Comment by Ranzdo** [comment]
Added an introduction for flags to the wiki.

**Comment by coaster3000** [comment]
Thankyou :D That helps so much.

I have to admit. If there was a list of command libraries out there. This one would prob be my number one favorite. Its very dynamic with such simplicity. Even if it has a bit of code (Extra code) added to a project. 

It is very very smooth,
