### ISSUE TITLE
Adjust Player Messages to be More Clear

### ISSUE THREAD

**Issue by ghost** [Ranzdo/MethodCommand#5]
1) verifiers="min[-10]|max[10]" player enters: "11" response: "The parameter [speed] must be equal or greater than 10"
It should be: "The parameter [speed] must be equal to or greater than -10" (bug)
Ideally it should be: "The parameter [speed] must be equal or greater than -10 and less than or equal to 10"
or "The parameter [speed] must be between or equal to -10 and 10"

2) When the argument is set to an integer and the player enters a double e.g. expected 5 given 5.00
It says: "The parameter [%p] is not a number"
It should say: "The parameter [speed] is not an integer"
Note that the argument was not named "[%p]" so that could be a bug?

3) When a player enters a command e.g. /flyspeed but does not enter the expected arguments e.g. /flyspeed [speed]
In addition to saying: "The argument [speed] is not defined (it has no default value)"
It should also have another line before that  which shows the usage information which should be: "Usage: /flyspeed [speed]"

**Comment by Ranzdo** [comment]
Fixed all the issues and I added also the range verifier which can be used to make a message like "The parameter [speed] must be equal or greater than -10 and less than or equal to 10" by doing verifiers="range[-10,10]".
